### ISSUE TITLE
Builder shouldn't quit on connection loss

### ISSUE THREAD

**Issue by Fuuzetsu** [haskell/ghc-builder#3]
Currently builder terminates if it loses connection which means that we have to check every now and again and manually restart it. It'd be nice if it just waited for a connection to come back and resume its regular duties.

**Comment by AlainODea** [comment]
@Fuuzetsu are you still experiencing this?  If not I can close this issue.

If so, how does this appear in logs when it disconnects?  My builders generally survive network outages.  I'm running them on a repurposed PC on a home network so there's nothing special shielding them from issues.  It's possible that SMF (service management framework) is restarting the service..

This code in **client.hs** already does indefinate connection retries with 5 second sleeps between attempts:

```haskell
`onConnectionDropped`
  do verbose' v user ("Connection dropped...sleeping for 5 seconds...")
    threadDelay (5 * 1000000)
    connLoop curDir baseDir user host
```
SOURCE: https://github.com/haskell/ghc-builder/blob/1f47fcfcec205da4654594fd470880f82e96d5c6/client/client.hs#L86-L89

```haskell
c host `onConnectionFailed`
  do verbose' v user ("Failed...sleeping for " ++ show secs ++ " seconds...")
    threadDelay (secs * 1000000)
    conn user host ((secs * 2) `min` 600)
```
SOURCE: https://github.com/haskell/ghc-builder/blob/1f47fcfcec205da4654594fd470880f82e96d5c6/client/client.hs#L93-L96

**Comment by Fuuzetsu** [comment]
@AlainODea I haven't used this in *years* so I don't know, sorry.

**Comment by AlainODea** [comment]
@Fuuzetsu no worries at all.
